= REST Docs
Andy Wilkinson;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[overview]]
== Overview

[[overview-host]]
=== Host

|===
| 환경 | Host

| Sandbox
| `https://sandbox-xxx-service.com`

| Beta
| `https://beta-xxx-service.com`

| Production
| `https://xxx-service.com`
|===

[[overview-http-status-codes]]
=== HTTP status codes

|===
| Status code | Usage

| `200 OK`
| successfully

| `400 Bad Request`
| Bad Request

| `500 Internal Server Error`
| Server Error
|===

[[overview-error-response]]
=== HTTP Error Response

operation::rest-document/sample-request[snippets='http-response,response-fields']

[[Member-API]]
== Member API

[[Member-단일조회]]
=== Member 단일 조회
operation::member-api-test/member_get[snippets='path-parameters,http-request,http-response,response-fields']

[[Member-페이징-조회]]
=== Member 페이징 조회
operation::member-api-test/member_get_all[snippets='http-request,request-parameters,http-response']


[[Member-생성]]
=== Member 생성
operation::member-api-test/member_create[snippets='http-request,request-fields,http-response']


[[Member-수정]]
=== Member 수정
operation::member-api-test/member_update[snippets='http-request,path-parameters,request-fields,http-response']


[[Admin-API]]
== Admin API

[[Admin-단일조회]]
=== Admin 단일 조회
operation::admin-api-test/given-admin-id_when-requesting-admin-info[snippets = 'http-request,http-response,path-parameters,response-fields']

[[Admin-페이징-조회]]
=== Admin 페이징 조회
operation::admin-api-test/given-nothing_when-requesting-every-admin-info[snippets='http-request,http-response,request-parameters']

[[Admin-생성]]
=== Admin 생성
operation::admin-api-test/given-sign-up-request_when-creating-admin[snippets='http-request,request-fields,http-response']

[[Admin-수정]]
=== Admin 수정
operation::admin-api-test/given-admin-id-and-modification-request_when-updating-admin[snippets='http-request,path-parameters,request-fields,http-response']